#!/usr/bin/env python3
"""Generate MANIFEST.json for the agent-workbench template.

Scope: only templates/agent-workbench/ is manifested.
templates/certification-pipeline/ is intentionally excluded — it is a
separate deliverable with its own integrity mechanism and is not tracked
by this manifest.

Walks the template directory tree, computes SHA256 hashes for every file,
and writes a manifest that can be used to verify workspace integrity and
detect when template files have been modified without updating the manifest.

Usage:
    .venv/Scripts/python scripts/generate_manifest.py
    .venv/Scripts/python scripts/generate_manifest.py --check  # verify only
"""

import argparse
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
_TEMPLATE_DIR = _REPO_ROOT / "templates" / "agent-workbench"
_MANIFEST_PATH = _TEMPLATE_DIR / "MANIFEST.json"

# Files to skip in the manifest (generated or user-specific)
# FIX-102: Also skip gitignored runtime files that won't exist in CI
_SKIP_FILES = {
    "MANIFEST.json",
    ".github/hooks/scripts/audit.jsonl",
    ".github/hooks/scripts/copilot-otel.jsonl",
    ".github/hooks/scripts/.hook_state.json",
}

# Directories to skip entirely
_SKIP_DIRS = {"__pycache__"}

# Security-critical files that the workspace upgrader will update
_SECURITY_CRITICAL_PREFIXES = (
    ".github/hooks/",
    ".github/instructions/",
    ".vscode/",
)

_SECURITY_CRITICAL_FILES = {
    ".github/hooks/require-approval.json",
    ".github/hooks/scripts/security_gate.py",
    ".github/hooks/scripts/zone_classifier.py",
    ".github/hooks/scripts/update_hashes.py",
    ".github/hooks/scripts/require-approval.ps1",
    ".github/hooks/scripts/require-approval.sh",
    ".github/instructions/copilot-instructions.md",
    ".vscode/settings.json",
}


def _sha256(file_path: Path) -> str:
    """Compute SHA256 hex digest for a file (CRLF-normalized to LF)."""
    data = file_path.read_bytes().replace(b"\r\n", b"\n")
    return hashlib.sha256(data).hexdigest()


def _is_security_critical(rel_path: str) -> bool:
    """Check if a relative path is a security-critical file."""
    if rel_path in _SECURITY_CRITICAL_FILES:
        return True
    return any(rel_path.startswith(p) for p in _SECURITY_CRITICAL_PREFIXES)


def generate_manifest() -> dict:
    """Walk template directory and build manifest dict."""
    files = {}
    for file_path in sorted(_TEMPLATE_DIR.rglob("*")):
        if not file_path.is_file():
            continue
        rel_path = str(file_path.relative_to(_TEMPLATE_DIR)).replace("\\", "/")
        if rel_path in _SKIP_FILES:
            continue
        if any(part in _SKIP_DIRS for part in Path(rel_path).parts):
            continue
        files[rel_path] = {
            "sha256": _sha256(file_path),
            "security_critical": _is_security_critical(rel_path),
        }

    manifest = {
        "_comment": "Auto-generated by scripts/generate_manifest.py. Do not edit manually.",
        "_scope": "Covers templates/agent-workbench/ only. templates/certification-pipeline/ is intentionally excluded.",
        "_generated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "template": "agent-workbench",
        "file_count": len(files),
        "files": files,
    }
    return manifest


def write_manifest(manifest: dict) -> None:
    """Write manifest to MANIFEST.json."""
    _MANIFEST_PATH.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"Manifest written: {_MANIFEST_PATH}")
    print(f"  Files tracked: {manifest['file_count']}")
    security_count = sum(
        1 for v in manifest["files"].values() if v.get("security_critical")
    )
    print(f"  Security-critical: {security_count}")


def check_manifest() -> bool:
    """Verify existing manifest matches current template files. Returns True if OK."""
    if not _MANIFEST_PATH.exists():
        print("ERROR: MANIFEST.json does not exist. Run without --check to generate.")
        return False

    existing = json.loads(_MANIFEST_PATH.read_text(encoding="utf-8"))
    current = generate_manifest()

    errors = []
    existing_files = existing.get("files", {})
    current_files = current["files"]

    for rel_path, entry in current_files.items():
        if rel_path not in existing_files:
            errors.append(f"UNTRACKED: {rel_path}")
        elif entry["sha256"] != existing_files[rel_path]["sha256"]:
            errors.append(f"CHANGED:   {rel_path}")

    for rel_path in existing_files:
        if rel_path not in current_files:
            errors.append(f"REMOVED:   {rel_path}")

    if errors:
        print("Manifest is OUT OF DATE:")
        for e in errors:
            print(f"  {e}")
        print(f"\n{len(errors)} discrepancy(ies). Run without --check to regenerate.")
        return False

    print("Manifest is up to date.")
    return True


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Generate or verify MANIFEST.json for templates/agent-workbench/. "
            "Note: templates/certification-pipeline/ is intentionally excluded from this manifest."
        )
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify existing manifest without regenerating.",
    )
    args = parser.parse_args()

    if args.check:
        sys.exit(0 if check_manifest() else 1)
    else:
        manifest = generate_manifest()
        write_manifest(manifest)


if __name__ == "__main__":
    main()
